package com.esewa.internship.gyalbusherpa.esewaIntern.week_3.day11_MultiThreading;

class myThread extends Thread{
}

public class F5_ThreadPriorities {
    /*

        every thread in java has some priority, it may be default priority generated by jvm or customized priority
        provided by programmer.
        The valid range of priority is 1 to 10, where 1 is min priority and 10 is max priority.
        Thread class defines the following constants to represent some standard priorities.
        Thread.MIN_PRIORITY -> 1
        Thread.NORM_PRIORITY -> 5
        Thread.MAX_PRIORITY -> 10

        Thread scheduler use the priorities while allocating processor.
        The thread which have the highest priority will get chance first.
        If two thread have same priority then we can't expect the execution order, it depends on thread scheduler.

        public final int getPriority()
        public final void setPriority(int p) -> allowed values is range 1 to 10.

        The default priority only for the main thread is 5
        But for all remaining threads, default priority will be inherited from parent to child, i.e. whatever
        priority parent has the same priority will be there for child

     */
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().getPriority());
        Thread.currentThread().setPriority(9);
        MyThread t = new MyThread();
        System.out.println(t.getPriority());
    }
}
