spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: PAYMENT-SERVICE

server:
  port: 8082

