spring:
  security:
    user:
      name: test
      password: test12

# Configuration for postgres database
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/spring_security
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'